// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel AgentUpdate

struct Agent
{
    float4 position;
    float4 velocity;
};

float dt;
RWStructuredBuffer<Agent> agents;

[numthreads(128,1,1)]
void AgentUpdate (uint3 id : SV_DispatchThreadID)
{
    Agent agent = agents[id.x];
    agent.velocity = float4(1,1,1,0);
    agent.position = agent.position + agent.velocity*dt;
    
    agents[id.x] = agent;
}
